import Navbar from "@/components/custom/Header/NavBar";
import "../styles/globals.scss";
import Footer from "@/components/custom/Footer/Footer";
export const metadata = {
  title: "Next Best Setup App",
  description: "Generated by surya malla",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
